import { DocumentConfig } from '../types/config';

export const DEFAULT_CONFIG: DocumentConfig = {
  global: {
    pageMargin: {
      top: 3.5 / 2.54,
      bottom: 3.0 / 2.54,
      left: 3.0 / 2.54,
      right: 2.5 / 2.54,
    },
    pageSize: {
      width: 21.0,
      height: 29.7,
      unit: 'cm',
    },
    baseFontCn: 'SimSun',
    baseFontEn: 'Times New Roman',
    horizontalRule: 'default',
    includeTableOfContents: true,
    header: {
      enabled: true,
      text: '网络综合课程设计',
      distance: 2.8 / 2.54,
      fontFamily: 'SimSun',
      fontFamilyEn: 'Times New Roman',
      fontSize: 10.5,
      alignment: 'center',
    },
    footer: {
      enabled: true,
      pageNumber: true,
      format: '第{page}页（共{pages}页）',
      distance: 2.2 / 2.54,
      fontFamily: 'SimSun',
      fontFamilyEn: 'Times New Roman',
      fontSize: 10.5,
      alignment: 'center',
      startAtBody: true,
    },
    tableOfContents: {
      maxLevel: 2,
      titleStyle: {
        fontFamily: 'SimHei',
        fontFamilyEn: 'Times New Roman',
        fontSize: 18,
        color: '#000000',
        bold: true,
        italic: false,
        lineSpacing: 1.2,
        spaceBefore: 12,
        spaceAfter: 12,
        alignment: 'center',
        firstLineIndent: 0,
      },
      levelStyles: {
        '1': {
          fontFamily: 'SimHei',
          fontFamilyEn: 'Times New Roman',
          fontSize: 12,
          color: '#000000',
          bold: true,
          italic: false,
          alignment: 'left',
          firstLineIndent: 0,
        },
        '2': {
          fontFamily: 'SimSun',
          fontFamilyEn: 'Times New Roman',
          fontSize: 12,
          color: '#000000',
          bold: false,
          italic: false,
          alignment: 'left',
          firstLineIndent: 2,
        },
      },
    },
    bodyStart: {
      firstHeadingAsTitle: true,
      restartPageNumberAfterToc: true,
      pageNumberStart: 1,
    },
    tableHeaderBold: false,
    normalizePunctuation: true,
  },
  styles: {
    documentTitle: {
      fontFamily: 'SimHei',
      fontFamilyEn: 'Times New Roman',
      fontSize: 18,
      color: '#000000',
      bold: true,
      italic: false,
      lineSpacing: 1.2,
      spaceBefore: 12,
      spaceAfter: 12,
      alignment: 'center',
      firstLineIndent: 0,
    },
    h1: {
      fontFamily: 'SimHei',
      fontFamilyEn: 'Times New Roman',
      fontSize: 18,
      color: '#000000',
      bold: true,
      italic: false,
      lineSpacing: 1.2,
      spaceBefore: 6,
      spaceAfter: 6,
      alignment: 'left',
      firstLineIndent: 0,
    },
    h2: {
      fontFamily: 'SimHei',
      fontFamilyEn: 'Times New Roman',
      fontSize: 16,
      color: '#000000',
      bold: true,
      italic: false,
      lineSpacing: 1.2,
      spaceBefore: 6,
      spaceAfter: 6,
      alignment: 'left',
      firstLineIndent: 0,
    },
    h3: {
      fontFamily: 'SimHei',
      fontFamilyEn: 'Times New Roman',
      fontSize: 12,
      color: '#000000',
      bold: true,
      italic: false,
      lineSpacing: 1.2,
      spaceBefore: 6,
      spaceAfter: 6,
      alignment: 'left',
      firstLineIndent: 0,
    },
    body: {
      fontFamily: 'SimSun',
      fontFamilyEn: 'Times New Roman',
      fontSize: 12,
      color: '#000000',
      bold: false,
      italic: false,
      lineSpacing: '22pt',
      spaceBefore: 0,
      spaceAfter: 0,
      alignment: 'left',
      firstLineIndent: 2,
    },
    code: {
      fontFamily: 'Courier New',
      fontFamilyEn: 'Courier New',
      fontSize: 10,
      color: '#000000',
      bold: false,
      italic: false,
      lineSpacing: 1.2,
      spaceBefore: 0,
      spaceAfter: 0,
      alignment: 'left',
      firstLineIndent: 0,
      backgroundColor: '#F5F7F9',
    },
    quote: {
      fontFamily: 'SimSun',
      fontFamilyEn: 'Times New Roman',
      fontSize: 12,
      color: '#000000',
      bold: false,
      italic: true,
      lineSpacing: 1.4,
      spaceBefore: 8,
      spaceAfter: 8,
      alignment: 'left',
      firstLineIndent: 0,
      backgroundColor: '#F5F7F9',
    },
    table: {
      fontFamily: 'SimSun',
      fontFamilyEn: 'Times New Roman',
      fontSize: 10.5,
      color: '#000000',
      bold: false,
      italic: false,
      lineSpacing: 1.2,
      spaceBefore: 0,
      spaceAfter: 0,
      alignment: 'center',
      firstLineIndent: 0,
    },
    caption: {
      fontFamily: 'KaiTi',
      fontFamilyEn: 'Times New Roman',
      fontSize: 10.5,
      color: '#000000',
      bold: true,
      italic: false,
      lineSpacing: 1.2,
      spaceBefore: 6,
      spaceAfter: 6,
      alignment: 'center',
      firstLineIndent: 0,
    },
  },
};
