export const PROVIDER_ICON_KEYS = [
  'alibaba',
  'anthropic',
  'aws',
  'azure',
  'baichuan',
  'chatglm',
  'cerebras',
  'claude',
  'cloudflare',
  'codegeex',
  'cohere',
  'copilot',
  'cursor',
  'deepinfra',
  'deepseek',
  'dify',
  'doubao',
  'fireworks',
  'gemini',
  'github',
  'googlecloud',
  'grok',
  'groq',
  'hailuo',
  'huggingface',
  'hunyuan',
  'hyperbolic',
  'internlm',
  'kling',
  'langchain',
  'llama',
  'meta',
  'minimax',
  'mistral',
  'moonshot',
  'nvidia',
  'ollama',
  'openai',
  'openrouter',
  'perplexity',
  'phind',
  'qwen',
  'replicate',
  'runway',
  'sambanova',
  'siliconflow',
  'skywork',
  'spark',
  'stability',
  'stepfun',
  'together',
  'trae',
  'vertexai',
  'wenxin',
  'windsurf',
  'xai',
  'yi',
  'zhipu',
] as const;

export type ProviderIconKey = typeof PROVIDER_ICON_KEYS[number];

export const PROVIDER_ICON_LABELS: Record<ProviderIconKey, string> = {
  alibaba: '阿里云',
  anthropic: 'Anthropic',
  aws: 'AWS',
  azure: 'Azure',
  baichuan: '百川',
  chatglm: 'ChatGLM',
  cerebras: 'Cerebras',
  claude: 'Claude',
  cloudflare: 'Cloudflare',
  codegeex: 'CodeGeeX',
  cohere: 'Cohere',
  copilot: 'Copilot',
  cursor: 'Cursor',
  deepinfra: 'DeepInfra',
  deepseek: 'DeepSeek',
  dify: 'Dify',
  doubao: '豆包',
  fireworks: 'Fireworks',
  gemini: 'Gemini',
  github: 'GitHub',
  googlecloud: 'Google Cloud',
  grok: 'Grok',
  groq: 'Groq',
  hailuo: 'Hailuo',
  huggingface: 'Hugging Face',
  hunyuan: '混元',
  hyperbolic: 'Hyperbolic',
  internlm: 'InternLM',
  kling: 'Kling',
  langchain: 'LangChain',
  llama: 'Llama',
  meta: 'Meta',
  minimax: 'MiniMax',
  mistral: 'Mistral',
  moonshot: 'Moonshot',
  nvidia: 'NVIDIA',
  ollama: 'Ollama',
  openai: 'OpenAI',
  openrouter: 'OpenRouter',
  perplexity: 'Perplexity',
  phind: 'Phind',
  qwen: 'Qwen',
  replicate: 'Replicate',
  runway: 'Runway',
  sambanova: 'SambaNova',
  siliconflow: '硅基流动',
  skywork: 'Skywork',
  spark: 'Spark',
  stability: 'Stability',
  stepfun: 'StepFun',
  together: 'Together',
  trae: 'Trae',
  vertexai: 'Vertex AI',
  wenxin: '文心',
  windsurf: 'Windsurf',
  xai: 'xAI',
  yi: 'Yi',
  zhipu: '智谱',
};

export const DEFAULT_PROVIDER_ICON_BY_ID: Record<string, ProviderIconKey> = {
  dashscope: 'alibaba',
  siliconflow: 'siliconflow',
  zhipu: 'zhipu',
  deepseek: 'deepseek',
  moonshot: 'moonshot',
  openai: 'openai',
  google: 'gemini',
};

export function isProviderIconKey(value: string | undefined): value is ProviderIconKey {
  return !!value && (PROVIDER_ICON_KEYS as readonly string[]).includes(value);
}

export function getProviderInitials(name: string): string {
  const trimmed = name.trim();
  if (!trimmed) return '?';
  const asciiWords = trimmed.match(/[A-Za-z0-9]+/g);
  if (asciiWords && asciiWords.length > 0) {
    return asciiWords.slice(0, 2).map((word) => word[0]).join('').toUpperCase();
  }
  return Array.from(trimmed).slice(0, 2).join('');
}
